version: "3"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - ${APP_PORT}
    environment:
      - TZ=${APP_TZ}
      - JAVA_TIMEZONE=America/Caracas
      - MB_DB_TYPE=${APP_DB_TYPE}
      - MB_DB_DBNAME=${APP_DB_DBNAME}
      - MB_DB_PORT=${APP_DB_PORT}
      - MB_DB_HOST=${APP_DB_HOST}
      - MB_DB_USER=${APP_DB_USER}
      - MB_DB_PASS=${APP_DB_PASS}
      # - MUID=$UID
      # - MGID=$GID
      # - MB_DB_FILE=/metabase-data/metabase.db
    restart: unless-stopped
    volumes:
      - ./data:/metabase-data
      - ./config:/metabase
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
