version: "3"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3005:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: your.host.com
      MB_DB_USER: user
      MB_DB_PASS: password
