version: "3"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3005:3000
    environment:
      - TZ=${APP_TZ}
      - MB_DB_TYPE=${APP_DB_TYPE}
      - MB_DB_DBNAME=${APP_DB_DBNAME}
      - MB_DB_PORT=${APP_DB_PORT}
      - MB_DB_HOST=${APP_DB_HOST}
      - MB_DB_USER=${APP_DB_USER}
      - MB_DB_PASS=${APP_DB_PASS}
