version: "3"
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ~/Configs/jdownloader-2:/config:rw
      - ~/Downloads:/output:rw
    restart: unless-stopped
