---
version: "2.1"
services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Caracas
      - MSDELAY=10000 #optional
      - MAXLINES=32 #optional
      - MAXCLIENTS=4096 #optional
      - LOGFILE=true #optional
      - BINDFAMILY= #optional
    volumes:
      - ./config:/config #optional
    ports:
      - 22:2222
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
