version: '3'
services:
  weblate:
    ports:
      - 8047:8080
    image: weblate/weblate
    tmpfs:
      - /app/cache
    volumes:
      - ./weblate-data:/app/data
    env_file:
      - ./environment
    restart: unless-stopped
    depends_on:
      - database
      - cache
  database:
    image: postgres:15-alpine
    env_file:
      - ./environment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  cache:
    image: redis:6-alpine
    restart: unless-stopped
    command: [redis-server, --save, '60', '1']
    volumes:
      - ./redis-data:/data
