#No logre instalarlo, problemas de config, revisar puertos y configuración del router a establecer
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      #puertos para DHCP
      #      - 67:67/udp
      #      - 68:68/tcp
      #      - 68:68/udp
      - 853:853/tcp
      - 3000:3000/tcp
    volumes:
      - ~/work:/opt/adguardhome/work
      - ~/conf:/opt/adguardhome/conf
    restart: unless-stopped
#    docker run --name adguardhome \
#    -v /work:/opt/adguardhome/work \
#    -v /conf:/opt/adguardhome/conf \
#    -p 53:53/tcp -p 53:53/udp \
#    -p 80:80/tcp -p 3000:3000/tcp \
#    -p 67:67/udp -p 68:68/tcp -p 68:68/udp \
#    -p 443:443/tcp \
#    -p 853:853/tcp \
#    -d adguard/adguardhome
