version: "3.8"
services:
  db:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASS}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_USER_PASS}
      TZ: ${APP_TZ}
    ports:
      - ${APP_PORT}
    volumes:
      - ./data:/var/lib/mysql
