version: "3"

services:
  nocodb-mysql:
    image: nocodb/nocodb:latest
    container_name: nocodb-mysql
    ports:
      - "8086:8080"
    environment:
      NC_AUTH_JWT_SECRET: "yourultrasecret"
    volumes:
      - ./data:/usr/app/data/
    restart: unless-stopped

